font_size 12.5

confirm_os_window_close 0
allow_remote_control socket
listen_on unix:/tmp/kitty
shell_integration enabled

scrollback_pager nvim
# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /home/$USER/.local/share/kitty/site/pack/core/opt/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --env NVIM_APPNAME=kitty --nvim-args -n
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
