#!/usr/bin/env python

import os, sys

def set_wallpaper(path):
    config = f'''preload = {path}\nwallpaper = eDP-1, {path}\nwallpaper = HDMI-A-1, {path}'''

    os.system(f"echo -e '{config}' > ~/.config/hypr/hyprpaper.conf")



if __name__ == '__main__':
    assert len(sys.argv) == 2
    set_wallpaper(sys.argv[1])
