#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

mount --bind /home/sivansh/dev/jail /home/sivansh/dev/jail
if [ ! -d /home/sivansh/dev/jail/tmp/.X11-unix ]; then
  mkdir /home/sivansh/dev/jail/tmp/.X11-unix
fi
mount --bind /tmp/.X11-unix /home/sivansh/dev/jail/tmp/.X11-unix
arch-chroot /home/sivansh/dev/jail su - sivansh
umount /home/sivansh/dev/jail/tmp/.X11-unix
umount /home/sivansh/dev/jail
