#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "rofi_wallpaper_selector [dir path]"
  exit 1
fi

wallpapers_dir=$1

selected_wallpaper=$(for a in $wallpapers_dir/*; do echo -en "$a\0icon\x1f$a\n" ; done | rofi -dmenu -theme ~/.config/rofi/wallpaper_selector.rasi)

echo $selected_wallpaper
~/scripts/update_theme $selected_wallpaper

