#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "update_theme [image path]"
  exit 1
fi

wal -n -i "$1" > /dev/null 2>&1
swww img --transition-type=any $(cat ~/.cache/wal/wal)
killall waybar
waybar -s ~/.cache/wal/style.css > /dev/null 2>&1 & disown
dunstctl reload
