[window]
# decorations = "None"
opacity = 1
dynamic_padding = true

[font]
size = 12

[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 130
lines = 35

# [font.bold]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold"
# 
# [font.bold_italic]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold Italic"
# 
# [font.italic]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Italic"
# 
# [font.normal]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Regular"
